### ISSUE TITLE
README typo

### ISSUE THREAD

**Issue by jakecorrenti** [bryanmontalvan/compsec#1]
"techmologies" -> "technologies"

**Comment by DanNguyen1** [comment]
Need this ASAP for our next sprint - can we get this fixed?

**Comment by bryanmontalvan** [comment]
> Need this ASAP for our next sprint - can we get this fixed?

Agreed, I'm getting our best engineers to tackle this issue. Not sure how this got passed our insanely expansive and **expensive** CI/CD pipeline 🥲
